# Copyright (C) 2017 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

language: cpp
dist: trusty

env:
  global:
    - CPPFLAGS='-DXML_POOR_ENTROPY'  # bad idea, do not copy!
    - CFLAGS='-g -pipe'
  matrix:
    - MODE=address
    - MODE=lib-coverage

addons:
  apt:
    packages:
      - docbook2x
      - dos2unix

script:
  - cd expat
  - ./buildconf.sh
  - ./qa.sh ${MODE}
